{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-insight-operator.fullname" . }}
  labels:
    {{- include "kube-insight-operator.labels" . | nindent 4 }}
rules:
  # Core API permissions for all components
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
      - serviceaccounts
      - pods
      - nodes
      - endpoints
      - namespaces
      - persistentvolumeclaims
      - persistentvolumes
      - events
      - limitranges
      - replicationcontrollers
      - resourcequotas
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  
  # Node-specific permissions for monitoring
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
  
  # Apps API group permissions
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  
  # Batch API group permissions for kube-state-metrics
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  
  # Networking API group permissions
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  
  # Storage API group permissions
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  
  # Permissions for RBAC management
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  
  # Permissions for ObservabilityStack CRD
  - apiGroups:
      - monitoring.monitoring.example.com
    resources:
      - observabilitystacks
      - observabilitystacks/status
      - observabilitystacks/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  
  # Permissions for non-resource URLs (Prometheus metrics scraping)
  - nonResourceURLs:
      - /metrics
      - /api
      - /api/*
    verbs:
      - get
  
  # Coordination API group for leader election
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{- end }}