apiVersion: v1
kind: Service
metadata:
  name: controller-manager-metrics
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - port: 8080
    targetPort: metrics
    name: metrics