# Default values for kube-insight-operator

# Operator configuration
operator:
  # Specify the image repository for the operator
  image:
    repository: johnwroge/kube-insight-operator
    tag: latest
    pullPolicy: IfNotPresent
  
  # Resource configuration for the operator
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  
  # Namespace where the operator will be deployed
  namespace: kube-insight-operator-system
  
  # Node selector for the operator
  nodeSelector: {}
  
  # Tolerations for the operator
  tolerations: []
  
  # Affinity settings for the operator
  affinity: {}

  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    fsGroup: 65532

  # Container security context
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532

# Service account settings
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# RBAC settings
rbac:
  # Specifies whether RBAC resources should be created
  create: true

# CRD settings
crd:
  # Specifies whether Custom Resource Definitions should be created
  create: true

# Default configuration for the ObservabilityStack CR
defaultStack:
  # Enable creation of a default ObservabilityStack CR
  create: false

  # Default ObservabilityStack configuration
  spec:
    prometheus:
      enabled: true
      storage: "10Gi"
      retention: "15d"
      nodeExporter:
        enabled: true
      kubeStateMetrics:
        enabled: true
    
    grafana:
      enabled: true
      adminPassword: "admin"
      serviceType: "ClusterIP"
      storage: "5Gi"
      defaultDashboards: true
      additionalDataSources:
      - name: "prometheus"
        type: "prometheus"
        url: "http://monitoring-test-prometheus:9090"
        isDefault: true
      - name: "tempo"
        type: "tempo"
        url: "http://monitoring-test-tempo:3200"
      - name: "loki"
        type: "loki"
        url: "http://monitoring-test-loki:3100"
    
    loki:
      enabled: true
      storage: "10Gi"
      retentionDays: 15
    
    promtail:
      enabled: true
      resources:
        cpuRequest: "100m"
        memoryRequest: "128Mi"
        cpuLimit: "200m"
        memoryLimit: "256Mi"
      scrapeKubernetesLogs: true
    
    tempo:
      enabled: true
      storage: "10Gi"
      retentionDays: 7
      resources:
        cpuRequest: "200m"
        memoryRequest: "512Mi"
        cpuLimit: "1"
        memoryLimit: "2Gi"