# Default values for kube-insight-operator

# Operator configuration
operator:
  # Specify the image repository for the operator
  image:
    repository: johnwroge/kube-insight-operator
    tag: latest
    pullPolicy: IfNotPresent
  
  # Resource configuration for the operator
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  
  # Namespace where the operator will be deployed
  namespace: kube-insight-operator-system
  
  # Node selector for the operator
  nodeSelector: {}
  
  # Tolerations for the operator
  tolerations: []
  
  # Affinity settings for the operator
  affinity: {}

  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    fsGroup: 65532

  # Container security context
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532

# Service account settings
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# RBAC settings
rbac:
  # Specifies whether RBAC resources should be created
  create: true

# CRD settings
crd:
  # Specifies whether Custom Resource Definitions should be created
  create: true

# Default configuration for the ObservabilityStack CR
defaultStack:
  # Enable creation of a default ObservabilityStack CR
  create: false

  # Default ObservabilityStack configuration
  spec:
    prometheus:
      enabled: true
      storage: "10Gi"
      retention: "15d"
      # Resource settings for Prometheus
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
      nodeExporter:
        enabled: true
        # Resource settings for Node Exporter
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
      kubeStateMetrics:
        enabled: true
        # Resource settings for kube-state-metrics
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
    
    grafana:
      enabled: true
      adminPassword: "admin"
      serviceType: "ClusterIP"
      storage: "5Gi"
      defaultDashboards: true
      # Resource settings for Grafana
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
      additionalDataSources:
      - name: "prometheus"
        type: "prometheus"
        url: "http://monitoring-test-prometheus:9090"
        isDefault: true
      - name: "tempo"
        type: "tempo"
        url: "http://monitoring-test-tempo:3200"
      - name: "loki"
        type: "loki"
        url: "http://monitoring-test-loki:3100"
    
    loki:
      enabled: true
      storage: "10Gi"
      retentionDays: 15
      # Resource settings for Loki
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
    
    promtail:
      enabled: true
      resources:
        cpuRequest: "100m"
        memoryRequest: "128Mi"
        cpuLimit: "200m"
        memoryLimit: "256Mi"
      scrapeKubernetesLogs: true
      # Optional: Add extra arguments
      extraArgs: []
    
    tempo:
      enabled: true
      storage: "10Gi"
      retentionDays: 7
      resources:
        cpuRequest: "200m"
        memoryRequest: "512Mi"
        cpuLimit: "1"
        memoryLimit: "2Gi"

# Storage configuration
storage:
  # Storage class to use for persistent volumes
  # If not set, the default storage class will be used
  className: ""
  
  # Access modes for persistent volumes
  accessModes:
    - ReadWriteOnce

# Advanced configuration
advanced:
  # Enable leader election for high availability
  leaderElection: true
  
  # Log level for the operator
  logLevel: "info"
  
  # Metrics configuration
  metrics:
    # Enable metrics service
    enabled: true
    # Service type for metrics
    serviceType: "ClusterIP"