apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-insight-operator.fullname" . }}
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "kube-insight-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "kube-insight-operator.selectorLabels" . | nindent 4 }}